name: dcdg
description: A tool to automatically generate class diagrams (like UML) from a Dart package.
version: 3.0.0
homepage: https://github.com/glesica/dcdg.dart
executables:
  dcdg:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^1.1.0
  args: ^2.0.0
  meta: ^1.0.0
  path: ^1.4.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0

