name: dartagram
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: George Lesica <email@example.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  analyzer: any
  build: ^1.0.0
  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
